name: Simple Amazon Link Generator
on:
  workflow_dispatch:
    inputs:
      max_links:
        description: 'Number of links'
        required: true
        default: '10'

jobs:
  generate-links:
    name: Generate Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Generate Amazon Links
      env:
        AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
        MAX_LINKS: ${{ github.event.inputs.max_links }}
      run: |
        echo "Starting link generation..."
        python amazon_scraper_scheduled.py
        
    - name: Commit Results
      run: |
        git config --global user.name 'Link Generator'
        git config --global user.email 'generator@example.com'
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Generated ${{ github.event.inputs.max_links }} Amazon links"
          git push
        fi
